const keyboard = [
  {
    keyRus: ']',
    keyRusCaps: ']',
    keyRusShift: '[',
    keyEng: '`',
    keyEngCaps: '`',
    keyEngShift: '~',
    code: 'Backquote',
    classes: 'btn',
  },
  {
    keyRus: '1',
    keyRusCaps: '1',
    keyRusShift: '!',
    keyEng: '1',
    keyEngCaps: '1',
    keyEngShift: '!',
    code: 'Digit1',
    classes: 'btn',
  },
  {
    keyRus: '2',
    keyRusCaps: '2',
    keyRusShift: '"',
    keyEng: '2',
    keyEngCaps: '2',
    keyEngShift: '@',
    code: 'Digit2',
    classes: 'btn',
  },
  {
    keyRus: '3',
    keyRusCaps: '3',
    keyRusShift: '№',
    keyEng: '3',
    keyEngCaps: '3',
    keyEngShift: '#',
    code: 'Digit3',
    classes: 'btn',
  },
  {
    keyRus: '4',
    keyRusCaps: '4',
    keyRusShift: '%',
    keyEng: '4',
    keyEngCaps: '4',
    keyEngShift: '$',
    code: 'Digit4',
    classes: 'btn',
  },
  {
    keyRus: '5',
    keyRusCaps: '5',
    keyRusShift: ':',
    keyEng: '5',
    keyEngCaps: '5',
    keyEngShift: '%',
    code: 'Digit5',
    classes: 'btn',
  },
  {
    keyRus: '6',
    keyRusCaps: '6',
    keyRusShift: ',',
    keyEng: '6',
    keyEngCaps: '6',
    keyEngShift: '^',
    code: 'Digit6',
    classes: 'btn',
  },
  {
    keyRus: '7',
    keyRusCaps: '7',
    keyRusShift: '.',
    keyEng: '7',
    keyEngCaps: '7',
    keyEngShift: '&',
    code: 'Digit7',
    classes: 'btn',
  },
  {
    keyRus: '8',
    keyRusCaps: '8',
    keyRusShift: ';',
    keyEng: '8',
    keyEngCaps: '8',
    keyEngShift: '*',
    code: 'Digit8',
    classes: 'btn',
  },
  {
    keyRus: '9',
    keyRusCaps: '9',
    keyRusShift: '(',
    keyEng: '9',
    keyEngCaps: '9',
    keyEngShift: '(',
    code: 'Digit9',
    classes: 'btn',
  },
  {
    keyRus: '0',
    keyRusCaps: '0',
    keyRusShift: ')',
    keyEng: '0',
    keyEngCaps: '0',
    keyEngShift: ')',
    code: 'Digit0',
    classes: 'btn',
  },
  {
    keyRus: '-',
    keyRusCaps: '-',
    keyRusShift: '_',
    keyEng: '-',
    keyEngCaps: '-',
    keyEngShift: '_',
    code: 'Minus',
    classes: 'btn',
  },
  {
    keyRus: '=',
    keyRusCaps: '=',
    keyRusShift: '+',
    keyEng: '=',
    keyEngCaps: '=',
    keyEngShift: '+',
    code: 'Equal',
    classes: 'btn',
  },
  {
    keyRus: 'Backspace',
    keyRusCaps: 'Backspace',
    keyRusShift: 'Backspace',
    keyEng: 'Backspace',
    keyEngCaps: 'Backspace',
    keyEngShift: 'Backspace',
    code: 'Backspace',
    classes: 'btn btn_func backspace',
  },
  {
    keyRus: 'Tab',
    keyRusCaps: 'Tab',
    keyRusShift: 'Tab',
    keyEng: 'Tab',
    keyEngCaps: 'Tab',
    keyEngShift: 'Tab',
    code: 'Tab',
    classes: 'btn btn_func tab',
  },
  {
    keyRus: 'й',
    keyRusCaps: 'Й',
    keyRusShift: 'Й',
    keyEng: 'q',
    keyEngCaps: 'Q',
    keyEngShift: 'Q',
    code: 'KeyQ',
    classes: 'btn',
  },
  {
    keyRus: 'ц',
    keyRusCaps: 'Ц',
    keyRusShift: 'Ц',
    keyEng: 'w',
    keyEngCaps: 'W',
    keyEngShift: 'W',
    code: 'KeyW',
    classes: 'btn',
  },
  {
    keyRus: 'у',
    keyRusCaps: 'У',
    keyRusShift: 'У',
    keyEng: 'e',
    keyEngCaps: 'E',
    keyEngShift: 'E',
    code: 'KeyE',
    classes: 'btn',
  },
  {
    keyRus: 'к',
    keyRusCaps: 'К',
    keyRusShift: 'К',
    keyEng: 'r',
    keyEngCaps: 'R',
    keyEngShift: 'R',
    code: 'KeyR',
    classes: 'btn',
  },
  {
    keyRus: 'е',
    keyRusCaps: 'Е',
    keyRusShift: 'Е',
    keyEng: 't',
    keyEngCaps: 'T',
    keyEngShift: 'T',
    code: 'KeyT',
    classes: 'btn',
  },
  {
    keyRus: 'н',
    keyRusCaps: 'Н',
    keyRusShift: 'Н',
    keyEng: 'y',
    keyEngCaps: 'Y',
    keyEngShift: 'Y',
    code: 'KeyY',
    classes: 'btn',
  },
  {
    keyRus: 'г',
    keyRusCaps: 'Г',
    keyRusShift: 'Г',
    keyEng: 'u',
    keyEngCaps: 'U',
    keyEngShift: 'U',
    code: 'KeyU',
    classes: 'btn',
  },
  {
    keyRus: 'ш',
    keyRusCaps: 'Ш',
    keyRusShift: 'Ш',
    keyEng: 'i',
    keyEngCaps: 'I',
    keyEngShift: 'I',
    code: 'KeyI',
    classes: 'btn',
  },
  {
    keyRus: 'щ',
    keyRusCaps: 'Щ',
    keyRusShift: 'Щ',
    keyEng: 'o',
    keyEngCaps: 'O',
    keyEngShift: 'O',
    code: 'KeyO',
    classes: 'btn',
  },
  {
    keyRus: 'з',
    keyRusCaps: 'З',
    keyRusShift: 'З',
    keyEng: 'p',
    keyEngCaps: 'P',
    keyEngShift: 'P',
    code: 'KeyP',
    classes: 'btn',
  },
  {
    keyRus: 'х',
    keyRusCaps: 'Х',
    keyRusShift: 'Х',
    keyEng: '[',
    keyEngCaps: '{',
    keyEngShift: '{',
    code: 'BracketLeft',
    classes: 'btn',
  },
  {
    keyRus: 'ъ',
    keyRusCaps: 'Ъ',
    keyRusShift: 'Ъ',
    keyEng: ']',
    keyEngCaps: '}',
    keyEngShift: '}',
    code: 'BracketRight',
    classes: 'btn',
  },
  {
    keyRus: 'ё',
    keyRusCaps: 'Ё',
    keyRusShift: 'Ё',
    keyEng: '\\',
    keyEngCaps: '|',
    keyEngShift: '|',
    code: 'Backslash',
    classes: 'btn',
  },
  {
    keyRus: 'Caps Lock',
    keyRusCaps: 'Caps Lock',
    keyRusShift: 'Caps Lock',
    keyEng: 'Caps Lock',
    keyEngCaps: 'Caps Lock',
    keyEngShift: 'Caps Lock',
    code: 'Caps Lock',
    classes: 'btn btn_func caps-lock',
  },
  {
    keyRus: 'ф',
    keyRusCaps: 'Ф',
    keyRusShift: 'Ф',
    keyEng: 'a',
    keyEngCaps: 'A',
    keyEngShift: 'A',
    code: 'KeyA',
    classes: 'btn',
  },
  {
    keyRus: 'ы',
    keyRusCaps: 'Ы',
    keyRusShift: 'Ы',
    keyEng: 's',
    keyEngCaps: 'S',
    keyEngShift: 'S',
    code: 'KeyS',
    classes: 'btn',
  },
  {
    keyRus: 'в',
    keyRusCaps: 'В',
    keyRusShift: 'В',
    keyEng: 'd',
    keyEngCaps: 'D',
    keyEngShift: 'D',
    code: 'KeyD',
    classes: 'btn',
  },
  {
    keyRus: 'а',
    keyRusCaps: 'А',
    keyRusShift: 'А',
    keyEng: 'f',
    keyEngCaps: 'F',
    keyEngShift: 'F',
    code: 'KeyF',
    classes: 'btn',
  },
  {
    keyRus: 'п',
    keyRusCaps: 'П',
    keyRusShift: 'П',
    keyEng: 'g',
    keyEngCaps: 'G',
    keyEngShift: 'G',
    code: 'KeyG',
    classes: 'btn',
  },
  {
    keyRus: 'р',
    keyRusCaps: 'Р',
    keyRusShift: 'Р',
    keyEng: 'h',
    keyEngCaps: 'H',
    keyEngShift: 'H',
    code: 'KeyH',
    classes: 'btn',
  },
  {
    keyRus: 'о',
    keyRusCaps: 'О',
    keyRusShift: 'О',
    keyEng: 'j',
    keyEngCaps: 'J',
    keyEngShift: 'J',
    code: 'KeyJ',
    classes: 'btn',
  },
  {
    keyRus: 'л',
    keyRusCaps: 'Л',
    keyRusShift: 'Л',
    keyEng: 'k',
    keyEngCaps: 'K',
    keyEngShift: 'K',
    code: 'KeyK',
    classes: 'btn',
  },
  {
    keyRus: 'д',
    keyRusCaps: 'Д',
    keyRusShift: 'Д',
    keyEng: 'l',
    keyEngCaps: 'L',
    keyEngShift: 'L',
    code: 'KeyL',
    classes: 'btn',
  },
  {
    keyRus: 'ж',
    keyRusCaps: 'Ж',
    keyRusShift: 'Ж',
    keyEng: ';',
    keyEngCaps: ':',
    keyEngShift: ':',
    code: 'Semicolon',
    classes: 'btn',
  },
  {
    keyRus: 'э',
    keyRusCaps: 'Э',
    keyRusShift: 'Э',
    keyEng: "'",
    keyEngCaps: '"',
    keyEngShift: '"',
    code: 'Quote',
    classes: 'btn',
  },
  {
    keyRus: 'Enter',
    keyRusCaps: 'Enter',
    keyRusShift: 'Enter',
    keyEng: 'Enter',
    keyEngCaps: 'Enter',
    keyEngShift: 'Enter',
    code: 'Enter',
    classes: 'btn btn_func enter',
  },
  {
    keyRus: 'Shift',
    keyRusCaps: 'Shift',
    keyRusShift: 'Shift',
    keyEng: 'Shift',
    keyEngCaps: 'Shift',
    keyEngShift: 'Shift',
    code: 'ShiftLeft',
    classes: 'btn btn_func shift-left',
  },
  {
    keyRus: 'я',
    keyRusCaps: 'Я',
    keyRusShift: 'Я',
    keyEng: 'z',
    keyEngCaps: 'Z',
    keyEngShift: 'Z',
    code: 'KeyZ',
    classes: 'btn',
  },
  {
    keyRus: 'ч',
    keyRusCaps: 'Ч',
    keyRusShift: 'Ч',
    keyEng: 'x',
    keyEngCaps: 'X',
    keyEngShift: 'X',
    code: 'KeyX',
    classes: 'btn',
  },
  {
    keyRus: 'с',
    keyRusCaps: 'С',
    keyRusShift: 'С',
    keyEng: 'c',
    keyEngCaps: 'С',
    keyEngShift: 'С',
    code: 'KeyC',
    classes: 'btn',
  },
  {
    keyRus: 'м',
    keyRusCaps: 'М',
    keyRusShift: 'М',
    keyEng: 'v',
    keyEngCaps: 'V',
    keyEngShift: 'V',
    code: 'KeyV',
    classes: 'btn',
  },
  {
    keyRus: 'и',
    keyRusCaps: 'И',
    keyRusShift: 'И',
    keyEng: 'b',
    keyEngCaps: 'B',
    keyEngShift: 'B',
    code: 'KeyB',
    classes: 'btn',
  },
  {
    keyRus: 'т',
    keyRusCaps: 'Т',
    keyRusShift: 'Т',
    keyEng: 'n',
    keyEngCaps: 'N',
    keyEngShift: 'N',
    code: 'KeyN',
    classes: 'btn',
  },
  {
    keyRus: 'ь',
    keyRusCaps: 'Ь',
    keyRusShift: 'Ь',
    keyEng: 'm',
    keyEngCaps: 'M',
    keyEngShift: 'M',
    code: 'KeyM',
    classes: 'btn',
  },
  {
    keyRus: 'б',
    keyRusCaps: 'Б',
    keyRusShift: 'Б',
    keyEng: ',',
    keyEngCaps: '<',
    keyEngShift: '<',
    code: 'Comma',
    classes: 'btn',
  },
  {
    keyRus: 'ю',
    keyRusCaps: 'Ю',
    keyRusShift: 'Ю',
    keyEng: '.',
    keyEngCaps: '>',
    keyEngShift: '>',
    code: 'Period',
    classes: 'btn',
  },
  {
    keyRus: '/',
    keyRusCaps: '?',
    keyRusShift: '?',
    keyEng: '/',
    keyEngCaps: '?',
    keyEngShift: '?',
    code: 'Slash',
    classes: 'btn',
  },
  {
    keyRus: '▲',
    keyRusCaps: '▲',
    keyRusShift: '▲',
    keyEng: '▲',
    keyEngCaps: '▲',
    keyEngShift: '▲',
    code: 'ArrowUp',
    classes: 'btn btn_func',
  },
  {
    keyRus: 'Shift',
    keyRusCaps: 'Shift',
    keyRusShift: 'Shift',
    keyEng: 'Shift',
    keyEngCaps: 'Shift',
    keyEngShift: 'Shift',
    code: 'ShiftRight',
    classes: 'btn btn_func shift-right',
  },
  {
    keyRus: 'Control',
    keyRusCaps: 'Control',
    keyRusShift: 'Control',
    keyEng: 'Control',
    keyEngCaps: 'Control',
    keyEngShift: 'Control',
    code: 'ControlLeft',
    classes: 'btn btn_func ctrl',
  },
  {
    keyRus: 'Option',
    keyRusCaps: 'Option',
    keyRusShift: 'Option',
    keyEng: 'Option',
    keyEngCaps: 'Option',
    keyEngShift: 'Option',
    code: 'AltLeft',
    classes: 'btn btn_func alt',
  },
  {
    keyRus: 'Command',
    keyRusCaps: 'Command',
    keyRusShift: 'Command',
    keyEng: 'Command',
    keyEngCaps: 'Command',
    keyEngShift: 'Command',
    code: 'MetaLeft',
    classes: 'btn btn_func meta',
  },
  {
    keyRus: '',
    keyRusCaps: '',
    keyRusShift: '',
    keyEng: '',
    keyEngCaps: '',
    keyEngShift: '',
    code: 'Space',
    classes: 'btn btn_func space',
  },
  {
    keyRus: 'Command',
    keyRusCaps: 'Command',
    keyRusShift: 'Command',
    keyEng: 'Command',
    keyEngCaps: 'Command',
    keyEngShift: 'Command',
    code: 'MetaRight',
    classes: 'btn btn_func meta',
  },
  {
    keyRus: 'Option',
    keyRusCaps: 'Option',
    keyRusShift: 'Option',
    keyEng: 'Option',
    keyEngCaps: 'Option',
    keyEngShift: 'Option',
    code: 'AltRight',
    classes: 'btn btn_func option',
  },
  {
    keyRus: '◄',
    keyRusCaps: '◄',
    keyRusShift: '◄',
    keyEng: '◄',
    keyEngCaps: '◄',
    keyEngShift: '◄',
    code: 'ArrowLeft',
    classes: 'btn btn_func',
  },
  {
    keyRus: '▼',
    keyRusCaps: '▼',
    keyRusShift: '▼',
    keyEng: '▼',
    keyEngCaps: '▼',
    keyEngShift: '▼',
    code: 'ArrowDown',
    classes: 'btn btn_func',
  },
  {
    keyRus: '►',
    keyRusCaps: '►',
    keyRusShift: '►',
    keyEng: '►',
    keyEngCaps: '►',
    keyEngShift: '►',
    code: 'ArrowRight',
    classes: 'btn btn_func',
  },
];

export default keyboard;
